In [2]:
import numpy as np
arr=np.array([2,4,6,8])
arr/2

array([1., 2., 3., 4.])

In [8]:
import numpy as np
list=np.array([2,3,6,8])

list*2

array([ 4,  6, 12, 16])

In [11]:
cars = ['ford','volvo','bmw']
x=cars[0]
print(x)

ford


In [13]:
mobil=['ford','volvo','bmw']
mobil[0]='toyota'
print(mobil)

['toyota', 'volvo', 'bmw']


In [15]:
cars = ['ford','volvo','bmw']
for x in cars:
    print(x)

ford
volvo
bmw


In [17]:
cars = ['ford','volvo','bmw']
x=len(cars)
print(x)

3


In [25]:
student=['pasca','riri','neva','najla','caca']
student[3]='dah'
student[0]='abdul'
student.append('fadhlan')
for x in student:
    print(x)

abdul
riri
neva
dah
caca
fadhlan


In [30]:
student=['pasca','riri','neva','najla','caca']
student[3]='dah'
student[0]='abdul'
student.append('fadhlan')
student.pop(1)
student.pop(3)
for x in student:
    print(x)

abdul
neva
dah
fadhlan


In [32]:
liverpool = ['nunez', 'salah', 'diaz', 'firmino']

x = liverpool.copy()
print(x)

['nunez', 'salah', 'diaz', 'firmino']


In [33]:
liverpool = ['nunez', 'firmino', 'jota']

x = liverpool.count("firmino")
print(x)

1


In [37]:
liverpool = ['jota', 'nunez', 'salah']

chelsea = ['aubameyang', 'ziyech', 'harvertz']

liverpool.extend(chelsea)
print(liverpool)

['jota', 'nunez', 'salah', 'aubameyang', 'ziyech', 'harvertz']


In [39]:
import numpy as np
#creatinglist
list=[1,2,3,4]

#creatingarray
sample_array=np.array(list)

print('list in python :',list)

print('numpy array in python:',sample_array)

list in python : [1, 2, 3, 4]
numpy array in python: [1 2 3 4]


In [41]:
#creatinglist
list_1=[1,2,3]
list_2=[5,6,7]
list_3=[9,10,11]

#creatingarray
sample_array=np.array([list_1,
                       list_2,
                       list_3])
print('numpy multi dimensional array in python\n ',sample_array)

numpy multi dimensional array in python
  [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
